# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
root: mistydew
title: parallel universe
quote: ソルト：無理は一番の、退屈しのぎだ。
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the ❤ parallel universe! Copyright &copy; 2019 mistydew.
  Powered by Jekyll. Hosted on GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mistydew.github.io" # the base hostname & protocol for your site

# Site footer
github: mistydew
cv: Curriculum Vitae 
email: mistydew@qq.com
subtitle: GC music diary
rss: Subscribe Feed
feedburner: mistydew
coffee: Buy me a coffee
btc: 1GC1iAZz9Wroy99bwJUzuLrqpmayUhjYbZ

# Site page baseurl
sitemap: "/sitemap.xml"
booklog: "/booklog.html"
quotes:  "/quotes.html"
about:   "/about.html"
resume:  "/resume.html"
gc:      "/gc/"
donate:  "/donate.html"

# Blog page baseurl
blog:     "/blog/"
archive:  "/blog/archive.html"
category: "/blog/category.html"
tagcloud: "/blog/tags.html"
feed:     "/blog/feed.html"
blogfeed: "/blog/feed.xml"

# Handling Reading
exclude: [LICENSE, README.md]
encoding : "utf-8"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n" # Excerpt/Abstract/Summary

# Outputting
permalink: /blog/:year/:month/:title.html
timezone: Asia/Shanghai # Beijing Time
