# Welcome to Jekyll 3.0.1!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# Site base
root: mistydew
title: parallel universe
quote: ソルト：無理は一番の、退屈しのぎだ。
subtitle: mistydew's blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the parallel universe ❤ mistydew's blog!
  Powered by Jekyll. Hosted on GitHub.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mistydew.github.io" # the base hostname & protocol for your site
bio: blockchain developer

# Site footer
github: mistydew
cv: Curriculum Vitae
email: mistydew@qq.com
gcmd: GC music diary
rss: Subscribe Feed
feedburner: mistydew
coffee: Buy me a coffee
btc: 1GC1iAZz9Wroy99bwJUzuLrqpmayUhjYbZ

# Site page baseurl
sitemap: "/sitemap.xml"
booklog: "/booklog.html"
quotes:  "/quotes.html"
about:   "/about.html"
resume:  "/resume.html"
gc:      "/gc/"
donate:  "/donate.html"

# About page
pgpkey: "/public_key.asc"
fingerprint: 7752 D418 D94C 33FB 8F6F 9197 44D9 CCA7 F81A 1FB3

# Blog page baseurl
blog:     "/blog/"
archive:  "/blog/archive.html"
category: "/blog/category.html"
tagcloud: "/blog/tags.html"
feed:     "/blog/feed.html"
atom:     "/blog/atom.xml"

# Build settings
# Handling Reading
exclude: [LICENSE, README.md]
encoding : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n" # Abstract / Summary
incremental: false

# Serving
port: 4000
host: 127.0.0.1

# Outputting
permalink: /blog/:year/:month/:title.html
timezone: Asia/Shanghai # Beijing Time
