# Welcome to Jekyll v3.0.1!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: 袁子晨
root: mistydew
name: 平行宇宙
title: parallel universe
blogname: 袁子晨的网络日志
subtitle: mistydew's blog
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the parallel universe!
  Powered by Jekyll. Hosted from GitHub.
  Copyright &copy; 2020 mistydew.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mistydew.github.io" # the base hostname & protocol for your site
squote: 人生は退屈すれば長く、充実すれば短い。
bquote: 無理は一番の”退屈しのぎ”だ。
email: mistydew@qq.com

# Page urls
about:    "/about.html"
booklog:  "/booklog.html"
quotes:   "/quotes.html"
blog:     "/blog/"
archive:  "/blog/archive.html"
category: "/blog/category.html"
feed:     "/blog/feed.html"
tag:      "/blog/tags.html"

# Where things are
source      : .
destination : ./_site
layouts_dir : _layouts
includes_dir: _includes
sass:
    sass_dir: _sass

# Handling Reading
exclude     : ["LICENSE", "README.md"]
encoding    : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md" # no spaces between exts

# Filtering Content
limit_posts: 0
future     : false

# Conversion
markdown         : kramdown
highlighter      : rouge
excerpt_separator: "\n\n"
incremental      : false

# Serving
port: 4000
host: 127.0.0.1

# Outputting
permalink: /blog/:year/:month/:title.html
timezone : Asia/Shanghai
