# Welcome to Jekyll v3.0.1!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author:
  name: Coshin
  github: encoshin
  e-mail: encoshin@mailo.com
title: Paraverse
subtitle: Coshin's Blog
hostname: encoshin.github.io
description: >- # this means to ignore newlines until "booklog:"
  Welcome to Coshin's parallel universe!

# Page urls
booklog:  "/booklog.html"
blog:     "/blog/"
archive:  "/blog/archive.html"
category: "/blog/category.html"
tag:      "/blog/tags.html"

# Where things are
source      : .
destination : ./_site
data_dir    : _data
layouts_dir : _layouts
includes_dir: _includes
sass:
    sass_dir: _sass

# Handling Reading
exclude     : ["LICENSE", "README.md"]
encoding    : "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
limit_posts: 0
future     : false

# Conversion
markdown         : kramdown
highlighter      : rouge
excerpt_separator: "\n\n"
incremental      : false

# Serving
port   : 4000
host   : 127.0.0.1
baseurl: "" # does not include hostname

# Outputting
permalink: /blog/:year/:month/:title.html
timezone : Asia/Shanghai
